# Generated by Django 4.2.3 on 2023-07-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hujjatlar',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'pdf'), ('xls', 'xls'), ('doc', 'doc'), ('jpg', 'jpg')], default='pdf', max_length=10),
        ),
    ]
