# Generated by Django 4.2.3 on 2023-07-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_hujjatlar_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hujjatlar',
            name='file_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('XLS', 'XLS'), ('DOC', 'DOC'), ('JPG', 'JPG')], default='PDF', max_length=10),
        ),
    ]
