# Generated by Django 4.2.3 on 2023-07-30 12:35

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_hujjatlar_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='info',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
