# Generated by Django 4.2.3 on 2023-07-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='info',
            field=models.TextField(),
        ),
    ]
