# Generated by Django 4.2.3 on 2023-07-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_hujjatlar_another_file_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hujjatlar',
            name='file_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('XLS', 'XLS'), ('DOC', 'DOC'), ('JPG', 'JPG')], default=False, max_length=10),
        ),
    ]
