# Generated by Django 4.2.3 on 2023-07-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_hujjatlar_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hujjatlar',
            name='file_type',
            field=models.CharField(choices=[('ㅤㅤㅤㅤㅤㅤ', 'ㅤㅤㅤㅤㅤㅤ'), ('PDF', 'PDF'), ('XLS', 'XLS'), ('DOC', 'DOC'), ('JPG', 'JPG')], default=False, max_length=10),
        ),
    ]
