# Generated by Django 4.2.3 on 2023-07-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_hujjatlar_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hujjatlar',
            name='another_file_type',
        ),
        migrations.AlterField(
            model_name='hujjatlar',
            name='file_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('XLS', 'XLS'), ('DOC', 'DOC'), ('JPG', 'JPG')], default='PDF', max_length=10),
        ),
    ]
