# Generated by Django 4.2.3 on 2023-07-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_hujjatlar_another_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hujjatlar',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code'),
        ),
        migrations.AlterField(
            model_name='hujjatlar',
            name='file_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('TXT', 'TXT'), ('XLS', 'XLS'), ('DOC', 'DOC'), ('JPG', 'JPG')], default='PDF', max_length=10),
        ),
    ]
