# Generated by Django 4.2.3 on 2023-07-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_hujjatlar_qr_code_alter_hujjatlar_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hujjatlar',
            name='qr_code',
            field=models.FileField(blank=True, null=True, upload_to='hujjatlar/'),
        ),
    ]
