# Generated by Django 4.2.3 on 2023-07-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_hujjatlar_url_alter_hujjatlar_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hujjatlar',
            name='url',
        ),
        migrations.AlterField(
            model_name='hujjatlar',
            name='name',
            field=models.CharField(default='http://127.0.0.1:8000/media/hujjatlar/<django.db.models.fields.files.FileField>', max_length=120),
        ),
        migrations.AlterField(
            model_name='hujjatlar',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code'),
        ),
    ]
