# Generated by Django 4.2.3 on 2023-07-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_hujjatlar_url_alter_hujjatlar_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hujjatlar',
            name='namee',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
