# Generated by Django 4.2.3 on 2023-07-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_hujjatlar_namee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hujjatlar',
            name='namee',
        ),
        migrations.AlterField(
            model_name='hujjatlar',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
